name: 'Chrome Update notification'

on:
  schedule:
    - cron: '0 23 * * *'
  push:
    branches: [ master ]


jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'setup-python'
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: 'install package'
        run: pip install requests
      - name: 'Get content'
        run: python script.py
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.126.com
          server_port: 25
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Chrome App (${{env.REPORT_DATE}})
          body: file://result.html
          to: test@moakt.co
          from: GitHub Actions
          content_type: text/html
